satellites:
  - name: Meteor M2-3
    norad: 57166
    frequency: 137.900e6
    bandwidth: 150e3
    sample_rate: 384e3
    lo_offset: 100e3
    priority: 10
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: lrpt
        container: ghcr.io/xarantolus/groundstation/satdump-decoder:latest
        args: --satellite_number M2-3 --fill_missing
        env:
          PIPELINE_NAME: meteor_m2_lrpt
        min_files: 10
      - name: x_lrpt
        container: ghcr.io/xarantolus/groundstation/satdump-decoder:latest
        args: --satellite_number M2-3 --fill_missing
        env:
          PIPELINE_NAME: meteor_m2-x_lrpt
        min_files: 10
      - name: x_lrpt_80k
        container: ghcr.io/xarantolus/groundstation/satdump-decoder:latest
        args: --satellite_number M2-3 --fill_missing
        env:
          PIPELINE_NAME: meteor_m2-x_lrpt_80k
        min_files: 10
    skip_iq_upload: true

  - name: Meteor M2-4
    norad: 59051
    frequency: 137.900e6
    bandwidth: 150e3
    sample_rate: 384e3
    lo_offset: 100e3
    priority: 10
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: lrpt
        container: ghcr.io/xarantolus/groundstation/satdump-decoder:latest
        args: --satellite_number M2-4 --fill_missing
        env:
          PIPELINE_NAME: meteor_m2_lrpt
        min_files: 10
      - name: x_lrpt
        container: ghcr.io/xarantolus/groundstation/satdump-decoder:latest
        args: --satellite_number M2-4 --fill_missing
        env:
          PIPELINE_NAME: meteor_m2-x_lrpt
        min_files: 10
      - name: x_lrpt_80k
        container: ghcr.io/xarantolus/groundstation/satdump-decoder:latest
        args: --satellite_number M2-4 --fill_missing
        env:
          PIPELINE_NAME: meteor_m2-x_lrpt_80k
        min_files: 10
    skip_iq_upload: true

  # AX100 satellites
  - name: AISTECHSAT-2
    norad: 43768
    frequency: 436.730e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]

  - name: CATSAT
    norad: 60246
    frequency: 437.185e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: INNOCUBE
    norad: 62616
    frequency: 435.950e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: K-HERO
    norad: 66660
    frequency: 437.180e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: Luojia-1
    norad: 43485
    frequency: 437.250e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: MIMAN
    norad: 52900
    frequency: 436.500e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: NUSHSAT-1
    norad: 63211
    frequency: 436.200e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: SNIPE-1
    norad: 56749
    frequency: 435.450e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: SNIPE-2
    norad: 56745
    frequency: 436.000e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: SNIPE-4
    norad: 56744
    frequency: 437.800e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: Suomi 100
    norad: 43804
    frequency: 437.775e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: UND ROADS 1
    norad: 64535
    frequency: 435.400e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: UND ROADS 2
    norad: 64549
    frequency: 435.400e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 6
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]
  - name: BEE-1000
    norad: 66650
    frequency: 436.500e6
    bandwidth: 1.024e6
    gain: 40
    sample_rate: 1.024e6
    lo_offset: 100e3
    priority: 4
    decoder:
      - container: ghcr.io/xarantolus/groundstation/waterfall:latest
      - name: ax100
        container: ghcr.io/xarantolus/groundstation/ax100-decoder:latest
        min_size_bytes: 1
        env:
          BAUD_RATE: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200]

nas_directory: /mnt/nas

pass_elevation_threshold_deg: 10
pass_start_threshold: 5
update_interval_hours: 24
