name: Podman Container Build

on:
  push:
  workflow_dispatch:
  schedule:
    # every 3 days at 2:19
    - cron: '19 2 */3 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman --version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Container Registry
        # Using environment variables for secrets
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login \
            ${{ env.REGISTRY }} \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Run setup script
        run: ./setup.sh --push
        env:
          PLATFORM: linux/amd64,linux/arm64
